trigger:
  branches:
    exclude:
      - main

pr:
  branches:
    exclude:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, World!
  displayName: 'Run a one-line script'
