trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Staging
  displayName: Staging Environment
  gates:
  - gate: ManualApprovalGate
    displayName: Manual Approval
    approvers: [mymanager]

- stage: Dev
  displayName: Dev Environment
  dependsOn: Staging
