trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Staging
  displayName: Staging Environment
  approvals:
  - approvers: [mymanager]

- stage: Dev
  displayName: Dev Environment
  dependsOn: Staging
