trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'my-artifact'

steps:
- checkout: self
- script:
    displayName: 'Build artifact'
    script: |
      # Build your artifact here
      # For example, if you are building a web application, you could use the following command:
      npm run build
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifact'
  inputs:
    PathtoPublish: $(System.DefaultWorkingDirectory)/artifacts/$(artifactName)
    ArtifactName: $(artifactName)


