trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Staging
  displayName: Staging Environment
  jobs:
  - job: DeployToStaging
    displayName: Deploy to Staging
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        azureSubscription: 'my-subscription-id'
        appType: webApp
        appName: 'my-webapp-name'
        package: '$(System.DefaultWorkingDirectory)/**/drop/my-webapp.zip'
        deploymentMethod: manual

- stage: Dev
  displayName: Dev Environment
  dependsOn: Staging
