trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Staging
  displayName: Staging Environment
  manualDeploymentTrigger: true

- stage: Dev
  displayName: Dev Environment
  dependsOn: Staging